### ISSUE TITLE
Very interesting adapter for the iobroker repo

### ISSUE THREAD

**Issue by simatec** [rde-master/ioBroker.checkmk#12]
Hello, 

your adapter is very interesting.  
Can you already test it?  

Do you guest before pushing them into the iobroker repo?

**Comment by rde-master** [comment]
Hello,
The adapter is in the middle of development. this version should be functional. But the settings are still missing, for example.
I also haven't written a documentary yet. at the moment it is possible to provide the status of all adapters check mk. I can also take my other states with me.

To test the adapter, simply add the ioBroker as a host and deploy the agent. If a check mk agent is already installed, the port should differ from the standard port.

The adapter is currently not in compact mode.

You are welcome to give me feedback.

----------------
Der Adapter ist in der Mitte der Entwicklung. diese version sollte funktionsfähig sein. Aber es fehlen noch z.B. die Einstellungen.
Ebenfalls habe ich noch keine Doku geschrieben. im moment kann man den status aller adapter check mk zur verfügung stellen. Ebenfalls kann mein weitere States mit auf nehmen.

Um den Adapter zu testen einfach den ioBroker als Host mit aufnehmen und den Agenten auswählen. Ist bereits ein check mk agent installiert so sollte der Port vom Standard Port abweichen.

Der Adapter geht derzeit nicht im compact Modus.

Du kannst mir gerne Feedback geben.

**Comment by simatec** [comment]
Ist der Agent egal oder benötigt der Adapter einen bestimmten Agenten?

**Comment by rde-master** [comment]
Nein, der Adapter selbst ist der Agent.
Du musst in check mk beim Host auswählen "mit Agent"

Wenn schon ein Agent installiert ist, dann musst du mit dem Port aufpassen, dass es da keinen Konflikt gibt.

**Comment by rde-master** [comment]
Der Adapter ist zum Testen nun bereit.
Ein Forum Thread wurde eröffnet.

**Comment by simatec** [comment]
Klasse … ich schaue mir das mal an
